FROM 108213052/pythonflask:v1

EXPOSE 5000

RUN adduser -D admin
USER admin
WORKDIR /home/admin

# ADD：將檔案加到 images 內
ADD . /admin
# ADD flaskServer /admin/flaskServer
# ADD Front /admin/Front

# ENV PYTHONUNBUFFERED 1

# 只有build 時使用，會執行此命令
COPY --chown=admin:admin requirements.txt /home/admin
ENV PATH="/home/admin/.local/bin:${PATH}"

# run container 時要執行的命令 COPY . /home/app
COPY --chown=admin:admin . /home/admin

# WORKDIR /home/admin/flaskServer
CMD python3 ./app.py